# Generated by Django 3.2.23 on 2024-02-21 10:58

from django.db import migrations, models
import django.db.models.deletion
import grimoirelab.core.scheduler.models
import grimoirelab_toolkit.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', grimoirelab.core.scheduler.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', grimoirelab.core.scheduler.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FetchTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.task')),
                ('backend', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('backend_args', models.JSONField(default=None, null=True)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Enqueued'), (3, 'Running'), (4, 'Completed'), (5, 'Failed')], default=1)),
                ('age', models.PositiveIntegerField(default=0)),
                ('executions', models.PositiveIntegerField(default=0)),
                ('num_failures', models.PositiveIntegerField(default=0)),
                ('job_id', models.CharField(default=None, max_length=128, null=True)),
                ('queue', models.CharField(default=None, max_length=128, null=True)),
                ('scheduled_datetime', models.DateTimeField(default=None, null=True)),
                ('interval', models.PositiveIntegerField(default=60)),
                ('max_retries', models.PositiveIntegerField(default=3, null=True)),
                ('last_execution', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'fetch_tasks',
            },
            bases=('scheduler.task',),
        ),
    ]
